Repository onulstore/Onulstore-FE-admin, pull requests merged in 2022-10, with the labels that each got.

#6 Item management #4
  package-lock.json
  package.json
  src/App.tsx
  src/components/Table/index.tsx
  src/components/Table/style.ts
  src/pages/ItemManagement/index.tsx
  src/pages/ItemManagement/style.ts
Labels: 📬 API, ✨ Feature

#3 ItemRegister #2
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/ChainedSelect/index.tsx
  src/components/ui/ChainedSelect/style.ts
  src/components/ui/ImageUploader/index.tsx
  src/components/ui/ImageUploader/style.ts
  src/components/ui/Input/index.tsx
  src/components/ui/Input/style.ts
  src/components/ui/Select/index.tsx
  src/components/ui/Select/style.ts
  src/main.tsx
  src/pages/ItemRegister/index.tsx
  src/pages/ItemRegister/style.ts
Labels: 📬 API, ✨ Feature

#9 Sign in #8
  package-lock.json
  package.json
  src/App.tsx
  src/components/FormInput/index.tsx
  src/components/FormInput/style.ts
  src/components/LargeBtn/index.tsx
  src/components/LargeBtn/style.ts
  src/components/icons/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.ts
  src/utils/Api/index.ts
  src/utils/constants.ts
Labels: 📬 API, ✨ Feature, 🎨 HTML & CSS

#10 HomeConfig #7
  package-lock.json
  package.json
  src/App.tsx
  src/components/BannerConfig/index.tsx
  src/components/BannerConfig/style.ts
  src/components/CurationConfig/index.tsx
  src/components/CurationConfig/style.ts
  src/components/MagazineConfig/index.tsx
  src/components/MagazineConfig/style.ts
  src/components/MagazineEdit/index.tsx
  src/components/MagazineEdit/style.ts
  src/components/MagazineForm/index.tsx
  src/components/MagazineForm/style.ts
  src/components/MagazineModal/index.tsx
  src/components/MagazineModal/style.ts
  src/components/MagazineRegister/index.tsx
  src/components/MagazineRegister/style.ts
  src/components/MagazineTable/index.tsx
  src/components/MagazineTable/style.ts
  src/components/MdConfig/index.tsx
  src/components/MdConfig/style.ts
  src/components/ReviewConfig/index.tsx
  src/components/ReviewConfig/style.ts
  src/components/TodayConfig/index.tsx
  src/components/TodayConfig/style.ts
  src/components/TodayModal/index.tsx
  src/components/TodayModal/style.ts
  src/components/TodayTable/index.tsx
  src/components/TodayTable/style.ts
  src/components/icons/index.tsx
  src/components/ui/ChainedSelect/index.tsx
  src/components/ui/ImageUploader/index.tsx
  src/components/ui/Input/index.tsx
  src/components/ui/Select/index.tsx
  src/components/ui/ToggleSwitch/index.tsx
  src/components/ui/ToggleSwitch/style.ts
  src/pages/HomeConfig/index.tsx
  src/pages/HomeConfig/style.ts
  src/pages/ItemManagement/index.tsx
  src/pages/ItemRegister/index.tsx
  src/store/index.ts
  src/store/slices/magazineSlice.ts
  src/store/slices/rootReducer.ts
Labels: 📬 API, ✨ Feature

#13 Axios instance #12
  src/utils/Api/index.ts
Labels: 📬 API, ✨ Feature

#18 #16 hotfix: 404 오류를 위한 설정
  public/_redirects
Labels: 🐞 BugFix, 🌏 Deploy
